export enum BucketNameEnums {
    BUCKET_IMAGE = 'BUCKET_IMAGE',
    BUCKET_VIDEO = 'BUCKET_VIDEO',
    BUCKET_DOCUMENT = 'BUCKET_DOCUMENT',
    BUCKET_REPORT = 'BUCKET_REPORT',
    BUCKET_REASON = 'BUCKET_REASON'
}
