export enum RolesEnums {
    ROLE_LEADER_SPECIAL = 'ROLE_LEADER_SPECIAL',
    ROLE_LEADER = 'ROLE_LEADER',
    ROLE_EMPLOYEE_SPECIAL = 'ROLE_EMPLOYEE_SPECIAL',
    ROLE_EMPLOYEE = 'ROLE_EMPLOYEE',
    ROLE_ADMIN = 'ROLE_ADMIN',
}

export const UNIT_SPECIAL = 'S101';
