stages:
  - build_image
  - restart_kube

build_image:
  stage: build_image
  script:
    - whoami
    - mvn clean install -DskipTests
    - docker build -t registry.gitlab.com/project-mgmt/deploy/pm-backend .
    - docker push registry.gitlab.com/project-mgmt/deploy/pm-backend

restart_kube:
  stage: restart_kube
  script:
    - kubectl -n pm-dev rollout restart deployment/pm-backend
